### SPDX-FileCopyrightText: 2024 PNED G.I.E.
###
### SPDX-License-Identifier: Apache-2.0

POST http://rems:3000/api/applications/invite-member
Accept: application/json
Content-Type: application/json
x-rems-api-key: 42
x-rems-user-id: eb4123a3-b722-4798-9af5-8957f823657a

{
    "application-id": 28
}