### SPDX-FileCopyrightText: 2024 PNED G.I.E.
###
### SPDX-License-Identifier: Apache-2.0

### Attach file to application
POST http://rems:3000/api/applications/add-attachment?application-id=28
Accept: application/json
Content-Type: multipart/form-data; boundary=MfnBoundry
x-rems-api-key: 42
x-rems-user-id: eb4123a3-b722-4798-9af5-8957f823657a

--MfnBoundry
Content-Disposition: form-data; name="file"; filename="06_dummy_attachment.txt"
Content-Type: text/plain

< ./06_dummy_attachment.txt
--MfnBoundry--

### Assign file to attachment field
### You must get the attachment id from the previous response
### and set the value of the field fld8
POST http://rems:3000/api/applications/save-draft
Content-Type: application/transit+json
## Session cookie and X-Csrf-Token are required
Cookie: rems-user-preferred-language=en; rems-user-preferred-language=en; ring-session=c0510a56-c391-4454-9b43-b308825dbc92; 7d6e23813298f396b0a54adedf7c65de=a45d54472b7be689623dbaea52902ca1; rems-user-preferred-language=en
X-Csrf-Token: Uv4QL75o4DKVd4sWNd1UezewiEhBc2CEXylxnfX+74i8qzt/BmsSntWV2LD8Kj+pRftb0oBvPTA/Vz1R

["^ ","~:application-id",28,"~:field-values",["~#list",[["^ ","~:form",2,"~:field","fld1","~:value",""],["^ ","^3",2,"^4","fld2","^5",""],["^ ","^3",2,"^4","fld3","^5",""],["^ ","^3",2,"^4","fld4","^5",""],["^ ","^3",2,"^4","fld5","^5",""],["^ ","^3",2,"^4","fld6","^5",""],["^ ","^3",2,"^4","fld7","^5",""],["^ ","^3",2,"^4","fld8","^5",""],["^ ","^3",2,"^4","option","^5",""],["^ ","^3",2,"^4","fld11","^5",""],["^ ","^3",2,"^4","fld12","^5",[]],["^ ","^3",2,"^4","fld13","^5",""],["^ ","^3",2,"^4","fld14","^5",""],["^ ","^3",2,"^4","fld15","^5",""],["^ ","^3",2,"^4","fld16","^5",""],["^ ","^3",2,"^4","fld17","^5",""]]],"~:duo-codes",["^2",[]]]