### SPDX-FileCopyrightText: 2024 PNED G.I.E.
###
### SPDX-License-Identifier: Apache-2.0

POST https://rems-demo.rahtiapp.fi/api/applications/save-draft
Content-Type: application/transit+json
## Session cookie and X-Csrf-Token are required
Cookie: rems-user-preferred-language=en; rems-user-preferred-language=en; ring-session=c0510a56-c391-4454-9b43-b308825dbc92; 7d6e23813298f396b0a54adedf7c65de=a45d54472b7be689623dbaea52902ca1; rems-user-preferred-language=en
X-Csrf-Token: Uv4QL75o4DKVd4sWNd1UezewiEhBc2CEXylxnfX+74i8qzt/BmsSntWV2LD8Kj+pRftb0oBvPTA/Vz1R

["^ ","~:application-id",28,"~:field-values",["~#list",[["^ ","~:form",2,"~:field","fld1","~:value",""],["^ ","^3",2,"^4","fld2","^5","test"],["^ ","^3",2,"^4","fld3","^5","test"],["^ ","^3",2,"^4","fld4","^5","asdasdasd"],["^ ","^3",2,"^4","fld5","^5",""],["^ ","^3",2,"^4","fld6","^5",""],["^ ","^3",2,"^4","fld7","^5",""],["^ ","^3",2,"^4","fld8","^5","11"],["^ ","^3",2,"^4","option","^5",""],["^ ","^3",2,"^4","fld11","^5","Option1 Option2 Option3"],["^ ","^3",2,"^4","fld12","^5",[[["^ ","~:column","col1","^5","asdasd"],["^ ","^6","col2","^5","asdasd"]],[["^ ","^6","col1","^5","adsasd"],["^ ","^6","col2","^5","asdasd"]]]],["^ ","^3",2,"^4","fld13","^5",""],["^ ","^3",2,"^4","fld14","^5",""],["^ ","^3",2,"^4","fld15","^5",""],["^ ","^3",2,"^4","fld16","^5",""],["^ ","^3",2,"^4","fld17","^5",""]]],"~:duo-codes",["^2",[["^ ","~:id","DUO:0000019","~:restrictions",["^2",[]]]]]]
