### SPDX-FileCopyrightText: 2024 PNED G.I.E.
###
### SPDX-License-Identifier: Apache-2.0

POST http://rems:3000/api/applications/save-draft
Accept: application/json
Content-Type: application/json
x-rems-api-key: 42
x-rems-user-id: 52cacbab-c440-4385-9d5f-46aa4930b0e4

{
    "application-id": 28
}
