### SPDX-FileCopyrightText: 2024 PNED G.I.E.
###
### SPDX-License-Identifier: Apache-2.0

GET http://rems:3000/api/my-applications
Accept: application/json
x-rems-api-key: 42
x-rems-user-id: eb4123a3-b722-4798-9af5-8957f823657a
