### SPDX-FileCopyrightText: 2024 PNED G.I.E.
###
### SPDX-License-Identifier: Apache-2.0

POST http://daam.local.onemilliongenomes.eu/api/users/create
Content-Type: application/json
x-rems-api-key: 42
x-rems-user-id: owner

{
  "userid": "52cacbab-c440-4385-9d5f-46aa4930b0e4",
  "name": "GDI Admin",
  "email": "your_email@example.com"
}

###
GET http://daam.local.onemilliongenomes.eu/api/users/active
Accept: application/json
x-rems-api-key: 42
x-rems-user-id: owner
