### SPDX-FileCopyrightText: 2024 PNED G.I.E.
###
### SPDX-License-Identifier: Apache-2.0

POST http://rems:3000/api/users/create
Content-Type: application/json
x-rems-api-key: 42
x-rems-user-id: owner

{
  "userid": "eb4123a3-b722-4798-9af5-8957f823657a",
  "name": "CKAN Admin",
  "email": "your_email@example.com"
}

###
GET http://rems:3000/api/users/active
Accept: application/json
x-rems-api-key: 42
x-rems-user-id: owner
